// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 17/10/2025, 4:18:22 p. m.
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["C:/Users/claud/OneDrive/Escritorio/TAREAS UNIVERSIDAD/8vo Semestre/Desarrollo Web/Tarea chat_rag Jan Carlos Marcos/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/claud/OneDrive/Escritorio/TAREAS UNIVERSIDAD/8vo Semestre/Desarrollo Web/Tarea chat_rag Jan Carlos Marcos/frontend/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/claud/OneDrive/Escritorio/TAREAS UNIVERSIDAD/8vo Semestre/Desarrollo Web/Tarea chat_rag Jan Carlos Marcos/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/claud/OneDrive/Escritorio/TAREAS UNIVERSIDAD/8vo Semestre/Desarrollo Web/Tarea chat_rag Jan Carlos Marcos/frontend/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/claud/OneDrive/Escritorio/TAREAS UNIVERSIDAD/8vo Semestre/Desarrollo Web/Tarea chat_rag Jan Carlos Marcos/frontend/plugins/**/*.{js,ts,mjs}","C:/Users/claud/OneDrive/Escritorio/TAREAS UNIVERSIDAD/8vo Semestre/Desarrollo Web/Tarea chat_rag Jan Carlos Marcos/frontend/composables/**/*.{js,ts,mjs}","C:/Users/claud/OneDrive/Escritorio/TAREAS UNIVERSIDAD/8vo Semestre/Desarrollo Web/Tarea chat_rag Jan Carlos Marcos/frontend/utils/**/*.{js,ts,mjs}","C:/Users/claud/OneDrive/Escritorio/TAREAS UNIVERSIDAD/8vo Semestre/Desarrollo Web/Tarea chat_rag Jan Carlos Marcos/frontend/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/claud/OneDrive/Escritorio/TAREAS UNIVERSIDAD/8vo Semestre/Desarrollo Web/Tarea chat_rag Jan Carlos Marcos/frontend/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/claud/OneDrive/Escritorio/TAREAS UNIVERSIDAD/8vo Semestre/Desarrollo Web/Tarea chat_rag Jan Carlos Marcos/frontend/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/claud/OneDrive/Escritorio/TAREAS UNIVERSIDAD/8vo Semestre/Desarrollo Web/Tarea chat_rag Jan Carlos Marcos/frontend/app.config.{js,ts,mjs}","C:/Users/claud/OneDrive/Escritorio/TAREAS UNIVERSIDAD/8vo Semestre/Desarrollo Web/Tarea chat_rag Jan Carlos Marcos/frontend/app/spa-loading-template.html"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;