from typing import Protocol, Iterable, Optional
from uuid import UUID

class DocumentRepository(Protocol):
    def save_pdf(self, *, title: str, filename: str, mime_type: str,
                 file_bytes: bytes, owner_id: Optional[UUID]) -> UUID: ...
    def add_chunks(self, document_id: UUID, chunks: Iterable[dict]) -> list[UUID]: ...
    def get_document(self, document_id: UUID) -> dict: ...
